[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.9.5",
    "fastapi>=0.120.4",
    "langcache>=0.10.1",
    "python-dotenv>=1.2.1",
    "redis>=7.0.1",
    "uvicorn>=0.32.1",
]
